---
- block:
    - name: Install apache2 package (Ubuntu)
      apt:
        name: apache2
        state: present
    - name: Start apache2 Service (Ubuntu)
      service:
        name: apache2
        state: started
    - name: Enable apache2 Service to Start on Boot (Ubuntu)
      service:
        name: apache2
        enabled: yes
    - name: Install wget package (Ubuntu)
      apt:
        name: wget
        state: present
  when: ansible_os_family == "Debian"
  tags: ubuntu
- block:
    - name: Install HTTPD package (RHEL)
      yum:
        name: httpd
        state: present
    - name: Start HTTPD Service (RHEL)
      service:
        name: httpd
        state: started
    - name: Enable HTTPD Service to Start on Boot (RHEL)
      service:
        name: httpd
        enabled: yes
    - name: Install wget package (RHEL)
      yum:
        name: wget
        state: present
  when: ansible_os_family == "RedHat"
  tags: redhat
