---
- name: Configure Web Server
  hosts: all
  become: yes
  
  roles:
    - apache
    - configurations
  tasks:
    - name: Download Apache Maven
      get_url:
        url: https://dlcdn.apache.org/maven/maven-4/4.0.0-rc-3/binaries/apache-maven-4.0.0-rc-3-bin.tar.gz
        dest: /opt/apache-maven-4.0.0-rc-3-bin.tar.gz
    - name: Extract Apache Maven
      unarchive:
        src: /opt/apache-maven-4.0.0-rc-3-bin.tar.gz
        dest: /opt/
        remote_src: yes
- name: Install Jenkins on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Install Java (required for Jenkins)
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes
    - name: Add Jenkins repository key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present
    - name: Add Jenkins repository to sources list
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes

