---
- name: Configure Web Server
  hosts: all
  become: yes
  
  roles:
    - apache
    - configurations
  tasks:
    - name: Download Apache Maven
      get_url:
        url: https://dlcdn.apache.org/maven/maven-4/4.0.0-rc-3/binaries/apache-maven-4.0.0-rc-3-bin.tar.gz
        dest: /opt/apache-maven-4.0.0-rc-3-bin.tar.gz
    - name: Extract Apache Maven
      unarchive:
        src: /opt/apache-maven-4.0.0-rc-3-bin.tar.gz
        dest: /opt/
        remote_src: yes
- name: Delete a file from remote host
  hosts: all
  become: yes
  tasks:
    - name: Remove a file if it exists
      file:
        path: /opt/hello.txt
        state: absent
