---
- block:
    - name: Install PHP and Apache PHP module
      apt:
        name:
          - php
          - libapache2-mod-php
        state: present
        update_cache: yes
    - name: Deploy index.php from template
      template:
        src: roles/apache/templates/index.php.j2
        dest: /var/www/html/index.php
        owner: root
        group: root
        mode: "0644"
    - name: Update bashrc file
      copy:
        src: roles/configurations/files/bashrc.txt
        dest: /etc/bash.bashrc
        owner: root
        group: root
        mode: "0644"
    - name: Update README.md file
      copy:
        src: roles/configurations/tasks/main.yml
        dest: /opt/hello.txt
        owner: root
        group: root
        mode: "0644"        
    - name: Restart apache2 Service (Ubuntu)
      service:
        name: apache2
        state: restarted
  when: ansible_os_family == "Debian"
  tags: ubuntu
- block:
    - name: Install HTTPD package (RHEL)
      yum:
        name: httpd
        state: present
    - name: Start HTTPD Service (RHEL)
      service:
        name: httpd
        state: started
    - name: Enable HTTPD Service to Start on Boot (RHEL)
      service:
        name: httpd
        enabled: yes
    - name: Install wget package (RHEL)
      yum:
        name: wget
        state: present
  when: ansible_os_family == "RedHat"
  tags: redhat
